### ISSUE TITLE
Add task creation date to all tasks

### ISSUE THREAD

**Issue by cronosnull** [dmwm/cms-htcondor-es#101]
In order to filter the task in a more natural way for the user, we need the task creation date (it need to be stored as a timestamp, in order to be used in grafana as time field). 
It can be generated from the CRAB_Workflow name, but maybe there is a more maintainable way to do this.

**Comment by stiegerb** [comment]
We can do that fairly easily here, yes. But we'd create a dependence on the format of CRAB_Workflow, so a better solution would be to create a new field in the ads at the same time as CRAB_Workflow gets filled. That might prevent some headache in the future. I wonder what @belforte thinks.

If we need something quickly now, we can patch it in here and fix it later. But note that this only works for some analysis jobs, not for all.

**Comment by belforte** [comment]
I supect there's no way that CRAB_Workflow format can changeso not to have a creation timestamp at beginning w/o breaking so many things that nobody willl want to fix them, i.e. it will never happen !

Indeed we recently added a classAd for the CRAB_TaskEndTime (when we kill and clean up) but not for the start since it is in the name.
Of course we can easily add tha N+1-th classAd, but I am not a fan of duplications

Why do you say that this will only work for some jobs but not for all ?

**Comment by stiegerb** [comment]
@belforte Ok, if we get your personal assurance that the format won't change, I'm happy.

CRAB_Workflow doesn't seem to be filled for about 1 in 4 analysis jobs.

**Comment by belforte** [comment]
uh !!!! are we sure that those are CRAB jobs ?
what the hell is happening ????? That'd be a very serious problem.

**Comment by belforte** [comment]
can you point me to one such job ?

**Comment by stiegerb** [comment]
Have a look yourself:
https://es-cms.cern.ch/kibana/goto/99cb2ec684a37c95ed131632facd0e77

**Comment by belforte** [comment]
those are not CRAB. AFAICT it is CMSConnect
https://es-cms.cern.ch/kibana/goto/bf0e477c0b8b33d4cd8a6a2cf111c4b9

**Comment by belforte** [comment]
I love the new CMS_SubmissionTool attribute !!

**Comment by belforte** [comment]
@cronosnull  you should filter on that CMS_SubmissionTool for the task dashboard. And if CMSConnect people ever care to give same functionality to their users, they need to make sure that those jobs provide the same set of attributes.

**Comment by cronosnull** [comment]
Sure, It is not in the new index, but I'll ask to be added along with the creation date.

**Comment by stiegerb** [comment]
@cronosnull Can you put together a PR with the changes we need? Should be easy to convert that date string into a UTC timestamp. Make sure to add it to the `date_vals` list also and to include it in the `running_fields`. If you need CMS_SubmissionTool also, we should add it to `running_fields` as well.
