### ISSUE TITLE
Exit code is being reported wrong.

### ISSUE THREAD

**Issue by cronosnull** [dmwm/cms-htcondor-es#103]
As @belforte noticed from the task monitoring dashboard, the exit code is being sent as the mod 256 of the actual code (maybe it was cast as byte in some part of the process).

**Comment by belforte** [comment]
you need to use  Chirp_CRAB3_Job_ExitCode  not the HTCondor job ExitCode

**Comment by stiegerb** [comment]
ExitCode is the condor exit code, which is mod 256. As Stefano wrote, you need to look at the chirped values for the 5-digit CMSSW exit codes. These are `Chirp_CRAB3_Job_ExitCode` for analysis jobs and `Chirp_WMCore_cmsRun_ExitCode` for production jobs.

See e.g. here:
https://github.com/dmwm/cms-htcondor-es/blob/master/src/htcondor_es/convert_to_json.py#L901

**Comment by cronosnull** [comment]
@stiegerb Can we make the change to report it in a field? (to make this in grafana is not as easy as it should).

**Comment by belforte** [comment]
I thought we had agreed to combine those in a single field, and discard the condor exit values, which is often wrong in a larger way than being mod256.

**Comment by stiegerb** [comment]
What are you proposing exactly? I see cases where the condor exit code is non-zero and both the chirped values are not set.

Of course we can add a field that combines the two chirped values, along the lines of
```python
exitcode = ad.get('Chirp_CRAB3_Job_ExitCode', ad.get('Chirp_WMCore_cmsRun_ExitCode', 0))
```

On the other hand I'm wondering where we would need that in Grafana? Where do we need to group by low-level exit codes and cover both production and analysis jobs?

**Comment by belforte** [comment]
welll. given that we have a common set of exit codes across analysis and production,  I thought that a single field is more convenient. Simply in Kibana/Grafana.. etc. I can use ExitCode w/o bothering
to remember if it was CRAB_Chirp or Chirp_CRAB every time ! Also avoids wasting storage.

All in all your record are by-job, it make sense to expect a job to have an exit code.
From my POV one job can have an ExitCode set by some intelligent piece of code like CRAB or WMA which is hopefully informative, or as you find only some default from HTCondor which personally I find never found useful. So while I am not advanced enough in python to parse your line, I had always imagined something like:
1. Chirp_CRAB.. and Chirp_WMCore... are never both set at same time, so if we find one, use that.
2. in lack. use HTCondor ExitCode
if there are jobs (CMSConnect ?, flockers from MIT ?) which reports nothing... it is certainly annoying, but we can't fix it, nor tell if those jobs were OK or not unless they tell us so.
Just try to avoid them from producing errors and make sure in our monitoring plots to keep them separate.

OTOH, this is clearly a soft matter, and you are in charge. Do what you feel good about, and as long as it is documented, users of the information will find their way around.

**Comment by stiegerb** [comment]
I agree, it would be nice to consolidate all this information into the same field. It's just that currently it's conflicting. E.g. your point 1 isn't the case, there are many analysis jobs that have a 3-digit WMCore exit code set, and there are jobs that have only the condor exit code.

So indeed we need to define some logic of priority. Why don't we add a temporary field and then have the longer term goal of having that replace our current ExitCode field.

I would propose something along your lines:
1. Use Chirp_CRAB3_Job_ExitCode if it is set (this is only set for analysis jobs, afaict)
2. Use Chirp_WMCore_cmsRun_ExitCode otherwise
3. If both unset, use ExitCode (condor)

So the code could be:
```python
results['ExitCodeConsolidated'] = ad.get('Chirp_CRAB3_Job_ExitCode', 
                                         ad.get('Chirp_WMCore_cmsRun_ExitCode', 
                                                 ad.get('ExitCode')))
```

**Comment by belforte** [comment]
+1
of course if final files in ES/Influx could be easier to type than ExitCodeConsolidated... I'd personally benefit !

**Comment by stiegerb** [comment]
See #104

**Comment by stiegerb** [comment]
After discussing with Brian, we decided to rather retain the condor exit code in a separate field (`CondorExitCode`) and overwrite the `ExitCode` field with the consolidated value. 

I assume everyone is ok with this.
