### ISSUE TITLE
Re-evaluate the need for constraining data for running/pending jobs

### ISSUE THREAD

**Issue by stiegerb** [dmwm/cms-htcondor-es#116]
We're currently maintaining a limited list of fields to be retained when processing the condor queues:
https://github.com/dmwm/cms-htcondor-es/blob/master/src/htcondor_es/convert_to_json.py#L423

And we're dropping any field not in that list when processing the queues:
https://github.com/dmwm/cms-htcondor-es/blob/master/src/htcondor_es/convert_to_json.py#L780-L781

(The behavior can be switched off by using the `--keep_full_queue_data` option for spider_cms.py)

I had introduced this as a means of speeding up the uploading of documents to MONIT (it cuts about a factor of 5 in volume, iirc) as we were having trouble staying within the 12 min cycle. However, we were still uploading from a VM hosted at UNL at that time, and the faster upload time from the CERN hosted VM to MONIT might have made this unnecessary.

To check, we could run a few cycles without culling the fields and see how much the performance suffers.

Another aspect to keep in mind, however, is that this would significantly increase the data volume needed on the MONIT side, since it affects a large majority of the documents we send.

**Comment by cronosnull** [comment]
It seems all the reports that come from the queues, regardless of the state, are reduced,  now that the completed jobs are being kept in the queue for a longer time that can cause problems (we'll see completed jobs without exit code or other relevant fields). Should we add all the relevant fields to the running_fields list (and, in that case, we should filter also the history) or just keep full queue data?

**Comment by stiegerb** [comment]
I would suggest to modify the code to account for that. I.e. check what status the job is in and only drop the fields if it's running/idle/held, but not if it's completed/error etc.

**Comment by mrceyhun** [comment]
It seems that current implementation and included fields is enough for the monitoring needs. Even though we can handle both history and queue query processing/uploading in 12 min period with no stress, data volume is big enough. We sometimes here how big our condor job monitoring data in ES cluster from MONIT team without asking for any action :) Therefore, I don't see any future improvement in this regard and closing the issue.
