### ISSUE TITLE
Create a way to identify the last update for a job.

### ISSUE THREAD

**Issue by cronosnull** [dmwm/cms-htcondor-es#117]
For the tasks' index, we are only taking the last status for each job. However, the order in which the messages are consumed is not enough to ensure that the last seen message is the actual last update. We starting using the `RecordTime`, and it worked when the status change, but for a completed job status updates always have the same `RecordTime` making that updates over completed jobs didn't get overwritten (as they have the same version). 

Currently, `DataCollection` and `RecordTime` use the `CompletionDate` for Completed jobs. Could we use the `_launch_time` for DataCollection (or a new field) and use it as a version hint?.

**Comment by belforte** [comment]
what's the definition of those various fiels `RecordTime, _luch_time, CompletionDate...` ?
We have a system with  buffers and queues and pipeline which may even change technology, Kaka now, something else later.. can't rely on messages being processed in any order.

**Comment by cronosnull** [comment]
- `RecordTime`: When the job exited the queue or when the JSON document was last updated, whichever came first. Use this field for time-based queries.
- `DataCollection`: Currently is similar, for record time it takes into account if it is Held, DataCollection don't (It is CompletionDate if there is one, else it is when the JSON document was last updated). 
- `CompletionDate` is a classad (it think is the time the job changed his status to completed) 
- `_launch_time` is the execution time of the spider process that sends the message. 
 There are some issues in the past related to these fields, perhaps @stiegerb can enlighten us about that.

**Comment by stiegerb** [comment]
`RecordTime` is defined [here:](https://github.com/dmwm/cms-htcondor-es/blob/master/src/htcondor_es/convert_to_json.py#L789-L805)
```python
def recordTime(ad):
    """
    RecordTime falls back to launch time as last-resort and for jobs in the queue
    For Completed/Removed/Error jobs, try to update it:
        - to CompletionDate if present
        - else to EnteredCurrentStatus if present
        - else fall back to launch time
    """
    if ad['JobStatus'] in [3, 4, 6]:
        if ad.get('CompletionDate', 0) > 0:
            return ad['CompletionDate']

        elif ad.get('EnteredCurrentStatus', 0) > 0:
            return ad['EnteredCurrentStatus']

    return _launch_time
```

`DataCollection` is the `CompletionDate` from the classad, if it exists, otherwise it's the launch time of the script.

`DataCollectionDate` is useless, it just equals to `RecordTime`. I assume Brian had added this originally as a placeholder and nobody cleaned it up since then.

Note that I also added the launch time of the spider script in the metadata: `metadata.spider_runtime`. You can use this to identify the last record for each job.

**Comment by cronosnull** [comment]
The `<CRAB_Retry +1>+<spider_runtime>` will work for both (tasks and overview) indexes. Today I met with the monit team and we agree that is better to have a version field in the document (so we can change the version schema if needed without modifying the flume definitions). It's not a pressing issue but can be an improvement (to maintain logic on our side).

**Comment by mrceyhun** [comment]
No update in the issue or problem in monitoring since a few years, closing...
