### ISSUE TITLE
Properly sort jobs in Grafana dashboard for task monitoring

### ISSUE THREAD

**Issue by lecriste** [dmwm/cms-htcondor-es#118]
Given the discussion in https://github.com/dmwm/CRABServer/issues/5860
we agree with @cronosnull to add a numerical field corresponding to the `CRAB_Id` string and sort jobs accordingly.

At the moment, the possible values of CRAB_Id are of two types:
- "1", "2", "3", ..., up to ~"10000"
- "n-1", "n-2", "n-3", ..., where n can be 0, 1, 2 or 3

and the overall order should be 0-1, 0-2, 0-3, 0-..., 1, 2, 3, ..., 1-1, 1-2, 1-3, 1-..., 2-1, 2-2, 2-3, 2-..., 3-1, 3-2, 3-3, 3-...

**Comment by belforte** [comment]
I think that also this other order could make sense
 0-1, 0-2, 0-3, 0-..., 1,  1-1, 1-2, 1-3, 1-...,2,  2-1, 2-2, 2-..., 3, 3-..., 4,..., 5 ....
I have no strong preference, maybe you can pick the one which leads to the most easy-to-read implementation ?

**Comment by lecriste** [comment]
Tail jobs (1-..., 2-..., 3-...) can be created and run only after standard jobs (1, 2, 3, ...) so, for users understanding, I prefer not to mess up the former with the latter in the table.

**Comment by cronosnull** [comment]
We can create a numerical field replacing the dash for dot, that will lead to @belforte's order.  

For @lecriste order, we will need to think in another way to transform the values but keep the semantics.  Maybe a string with 0 padded numbers?
0-1,0-2,0-3,00001,00002,00003,...,09999,1-1...3-3

**Comment by lecriste** [comment]
> For @lecriste order, we will need to think in another way to transform the values but keep the semantics. Maybe a string with 0 padded numbers?

I have no preference, whatever is best for you.

**Comment by belforte** [comment]
@lecriste matter of taste. If you look at things when all is done it makes sense to see one job with its tail, then N jobs which needed no tail etc. If you are more focussed on the evolution of things as they happen, all tails later is more convenient. Jobs do not start in numerical order anyhow, and tails start to be submitted when 50% of the initial jobs are done. And if you have >1k jobs in the task, you may never want to look at the full table anyhow. Anyhow.. too may cooks spoil the cooking. Your call here !

**Comment by lecriste** [comment]
> @lecriste matter of taste. If you look at things when all is done it makes sense to see one job with its tail, then N jobs which needed no tail etc.

Just to be clear: there is no such "job with its tail". The first tail jobs (1-...) are tail of the main jobs (1, 2, 3, ...) as a whole, not of a particular one; the second tail jobs (2-...) are tail of all the first tail jobs, etc.

**Comment by belforte** [comment]
THANKS !!! I clearly misunderstood big time :-(   Sorry for my confusion.
Whatever you find to make things more clear to user, the better, maybe that way I will also remember

**Comment by belforte** [comment]
is this new index going to be exposed to users, or only used internally and in the table you keep showing 0-1, 5, 2-33 etc. ?
in case maybe this:
 0-x maps to 0.x (x is in 1-5)
 N maps to N (N is always less then 10K, not sure we may ever need/want to relax)
 N-M maps to N*10^5+M (so if we ever go over 10K, no worry, or even 10^6)

**Comment by lecriste** [comment]
> is this new index going to be exposed to users, or only used internally and in the table you keep showing 0-1, 5, 2-33 etc. ?

The latter.

**Comment by cronosnull** [comment]
![image](https://user-images.githubusercontent.com/4405564/57841315-99dce300-77ca-11e9-8249-e1964660dd1a.png)
in the values 1-X, X can be also from 1 to 9999?  should I format also that part to keep the order?
![image](https://user-images.githubusercontent.com/4405564/57842602-2d171800-77cd-11e9-9e5f-1f0005c333ea.png)

**Comment by lecriste** [comment]
LGTM

**Comment by belforte** [comment]
I surely do not understand how numerical sorting may put  0004736 before 3.00003 . But as long as it works... I would recommend to have some comments in the code about what you try to do and why, if someone like me reads this 3 years from now it will be very hard to figure out the reason for those formats.

**Comment by cronosnull** [comment]
Agree, I'll add them and make another commit tomorrow.


-- 
Christian
https://christian-ariza.net
