### ISSUE TITLE
CRAB_TaskCreationDate should be UTC timestamp

### ISSUE THREAD

**Issue by cronosnull** [dmwm/cms-htcondor-es#132]
Changes in https://github.com/dmwm/cms-htcondor-es/pull/128/commits/e75c68bede340c8cae56bfc220c24fcb99352f46  regarding the timezone (`get_creation_time_from_taskname`) did not make any difference.  We can remove the pytz dependency, and use: 

```python
import calendar
#...
calendar.timegm(_naive_date.timetuple())
```

**Comment by belforte** [comment]
@cronosnull the data-time string at beginning of task name is in UTC
https://github.com/dmwm/CRABServer/blob/master/src/python/ServerUtilities.py#L363-L369

I am sorry if we ever communicate otherwise :-(

**Comment by cronosnull** [comment]
Yes, the problem was with the time function in python that assumed that the time tuple was in local time (ignoring the timezone) with the change in #133 this should be solved.
