### ISSUE TITLE
Setting new filter for all condor job monitoring queries: JobUniverse==5

### ISSUE THREAD

**Issue by mrceyhun** [dmwm/cms-htcondor-es#197]
As suggested by @belforte  in MM(Distrubuted Analysis channel), we are planning to put JobUniverse==5 constraint to our query scripts that query Condor Schedds, both queue and history.

As CMS Monitoring&Analytics team, we are just the operator of this Condor Job Monitoring. That's why, we would like to get confirmation from all stakeholders.

You can see Completed jobs with JobUniverse is different than 5 in [1] and see other jobs with JobUniverse is different than 5 in [2] 

[1] https://es-cms.cern.ch/kibana/goto/9916fa1438a0d470cf620150e2ec8fb7
[2] https://monit-opensearch.cern.ch/dashboards/goto/9f7d3eaf122501164b28e0cb84b616b5?security_tenant=global

fyi @leggerf @brij01 

- Ceyhun

**Comment by belforte** [comment]
let me translate in English, so that people outside this restricted group may understand: the change will show ALL and ONLY jobs which run in the so called GlobalPool.

I am not aware of anybody but CRAB to be using other condor universes in the schedulers which we monitor, and people who do not know what we are talking about do no need to worry.

**Comment by belforte** [comment]
I gave a quick look at [1] and it looks that (as expected) those are all CRAB jobs. Does this settle the "who needs to be told" ?

**Comment by mrceyhun** [comment]
Thanks Stefano. 
In my last checks for 'JobUniverse != 5' , I see hammercloud test jobs other than Analysis jobs. Those will be filtered out too?

[3] https://es-cms.cern.ch/kibana/goto/22016c1617f071c1e7bb1f348c4ee2a1
[4] https://monit-opensearch.cern.ch/dashboards/goto/19cc6cac4c1a021e6e09062c92697974?security_tenant=global

**Comment by belforte** [comment]
yes, still CRAB submissions. We use universes 7 and 12 internally, but what people call "jobs" only run in universe==5. We have our own monitoring of things in those extra-universes

**Comment by mrceyhun** [comment]
Thanks @belforte , I opened a https://github.com/dmwm/cms-htcondor-es/pull/198 . I will run a full test before deploy it.

At the beginning, i thought there were also production jobs in different universes, but no. That's why I wanted to get confirmation from all stakeholders. It is clear now :)

**Comment by leggerf** [comment]
hi guys, I had a look at the old google sheet where we agreed on job monitoring attributes:

https://docs.google.com/spreadsheets/d/1x73SxboZqNvpYKHmaJ9PioT3itpw4qQrTjUecnKLTi4/edit?usp=sharing

at the time, there seemed to be a need for jobs other than in the Global Pool (column Pool).

I have to admit I do not remember details, but from the column it seems that there are other jobs that also need to be monitored (like volunteer, HEP cloud...). Or am I missing something here?

**Comment by belforte** [comment]
@leggerf you are correct. Sorry for my bad wording. Jobs in other pools still exist (i.e. GlobalPool vs. ITB vs. Tier0 vs... ) but this is another classAd that needs to be set in condor (or derived from the scheduler host name). All of those jobs still run in Vanilla condor universe, i.e. `jobUniverse==5`. 

Another way to look at it, each schedule machines has a pool of resources it schedules jobs on. So far in CMS we only schedule jobs which execute users applications (users includes WMA) on jobUniverse==5. This is how things work with glideinWMS pilots. Should we add one day schedulers other that those connected to pilots.. we may need to revisit the jobUniverse choice. I do not know of any plans in that direction, though.

**Comment by leggerf** [comment]
tnx @belforte for explaining it (again) so nicely. Hope will remember next time. @mrceyhun, I'm fine with PR #198

**Comment by mrceyhun** [comment]
Ok. As agreed, I merged https://github.com/dmwm/cms-htcondor-es/pull/198 and will apply in an hour. So, [other universes](https://github.com/dmwm/cms-htcondor-es/blob/master/src/htcondor_es/convert_to_json.py#L569-L581) will not be monitored via Spider(cms-htcondor-es) anymore.

**Comment by mrceyhun** [comment]
Done
