### ISSUE TITLE
Use CMS_extendedTaskType to support physics job task types

### ISSUE THREAD

**Issue by khurtado** [dmwm/cms-htcondor-es#215]
At present, physics task types are supported via:

https://github.com/dmwm/cms-htcondor-es/blob/master/src/htcondor_es/convert_to_json.py#L682-L684

WMCore has recently added support for this. The classad is called: `CMS_extendedJobType` and it shows the physics types when this is a production/processing job, or just the WMCOre job type (LogCollect, Merge, etc) when it is not.

We would need to replace the current `CMS_TaskType` in the code lines above with this new classad `CMS_extendedJobType` and still fallback to the guessTaskType function until this feature is fully propagated.
 Do I understand correctly that `CMS_TaskType` was a placeholder for a future WMCore native implementation of this by the way? I don't see this classad in the jobs in condor. 

Documentation can be found below:
https://github.com/dmwm/WMCore/wiki/Job-task-type-characterization-based-on-cmsDriver-command-line-arguments

But it basically support the following physics types (and a combination of them)

Physics types:

- GEN
- SIM
- DIGI_nopileup
- DIGI_premix
- DIGI_classicalmix
- RECO
- MINIAOD
- NANOAOD
- UNKNOWN

**Comment by nikodemas** [comment]
I can see the `CMS_TaskType` fields exists in some of the jobs (see [this](https://monit-opensearch.cern.ch/dashboards/app/discover?security_tenant=global#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15h,to:now))&_a=(columns:!(_source),filters:!(),index:dd1ba850-d169-11ea-966a-e1c0a7950cea,interval:auto,query:(language:lucene,query:'_exists_:data.CMS_TaskType'),sort:!())) and [this](https://es-cms.cern.ch/dashboards/app/discover?security_tenant=global#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15h,to:now))&_a=(columns:!(_source),filters:!(),index:'0f3117a0-d2e6-11ed-bdae-e3cf8c07f2fc',interval:auto,query:(language:lucene,query:'_exists_:CMS_TaskType'),sort:!()))) and it is not filled by us, so it comes from somewhere earlier. Should we therefore check for the value in `CMS_TaskType` before using the `guessTaskType()` function?

```python3
result["TaskType"] = result.get(
    "CMS_extendedJobType",
    result.get(
        "CMS_TaskType",
        guessTaskType(ad) if not analysis else result["CMS_JobType"],
    ),
)
```

**Comment by khurtado** [comment]
@nikodemas Ah, that's true! CRAB analysis jobs do report `CMS_TaskType`. I have updated my PR with your suggestions changes. Thanks for catching that.

**Comment by nikodemas** [comment]
Can it be that we also need to switch places between CRAB analysis `CMS_TaskType` and WMCore's `CMS_extendedJobType`, so that `CMS_TaskType` would be taken first and only if it doesn't exist, then we take the `CMS_extendedJobType`?
Maybe this is a question for @belforte as well

**Comment by belforte** [comment]
IMHO we should have a definition of what we want those attributes mean.
CRAB sets CMS_TaskType based on initial discussion as "cmsRun" or "script".
This is not particularly useful and surely not aligned with the list in CMS_extendedJobType from WMA.
Part of this is that "task" means different things for CRAB and WMA.

If it helps, we can surely stop filling that in CRAB !

**Comment by nikodemas** [comment]
Thanks for the explanation, the current updates should be OK then.
I will merge the PR and deploy the changes then.

**Comment by nikodemas** [comment]
@khurtado I can't see `CMS_extendedJobType` field in our monitored jobs, does it mean that the feature is not yet fully propagated?

**Comment by khurtado** [comment]
@nikodemas Yes, central services were updated with the new changes, so this new data is in the ReqMgr2 service already, but it's not getting propagated to condor since the WMAgents have not been updated yet. @amaltaro When is the new WMAgent production release?

**Comment by nikodemas** [comment]
I can see the new release and that the fields are getting filled now. Thanks!

**Comment by nikodemas** [comment]
Hi @khurtado @amaltaro, I would like to come back to this issue - I can see that `CMS_extendedJobType` quite often has `UNKNOWN` value and then it gets propagated to the `TaskType` field (see [here](https://monit-opensearch.cern.ch/dashboards/goto/09704dac49c9fe405f7dfd60cc2c43ec)). Would it make sense to update [this part](https://github.com/dmwm/cms-htcondor-es/blob/40290be4c7f3e3fa0f9f394c10f45a39b7ee6860/src/htcondor_es/convert_to_json.py#L685-L691) in the code so that in occasions when `CMS_extendedJobType` is `UNKNOWN` the [`guessTaskType(ad)`](https://github.com/dmwm/cms-htcondor-es/blob/40290be4c7f3e3fa0f9f394c10f45a39b7ee6860/src/htcondor_es/convert_to_json.py#L1008-L1052) function would be used? So I think in all of the OpenSearch examples that I linked the `TaskType` would become `DataProcessing` instead of `UNKNOWN`.

FYI @leggerf @brij01
