### ISSUE TITLE
CRAB_Id can be a string now

### ISSUE THREAD

**Issue by stiegerb** [dmwm/cms-htcondor-es#33]
Easiest solution is to move it from `int_vals` to `string_vals`:
https://github.com/bbockelm/cms-htcondor-es/blob/master/src/htcondor_es/convert_to_json.py#L111

We'd then need to re-index the older ES indices to follow the change.

**Comment by stiegerb** [comment]
Also `Rank` now appears as `'Mips'` strings.

**Comment by bbockelm** [comment]
Hi Benjamin,

Should we try to merge this at a month-boundary?  Otherwise, we'll lose records when/if the ES team aggregates daily indices into monthly ones ... right?

Brian

**Comment by stiegerb** [comment]
Hi Brian,
What do you propose? Changing them to be string fields?
Anyway, I agree it would be best to do this at the end of the month.

Cheers,
Benjamin

**Comment by bbockelm** [comment]
Yup, let's prepare a new PR now and merge it at the beginning of July.

**Comment by stiegerb** [comment]
Ok, I updated #34 to include `Rank`, and rebased it to master.
