### ISSUE TITLE
Jobs missing in MONIT

### ISSUE THREAD

**Issue by belforte** [dmwm/cms-htcondor-es#69]
Seems we sare still far from having full accounting of jobs in MONIT.

While investigating a problem with glideinWms
https://ggus.eu/index.php?mode=ticket_info&ticket_id=138535
I tried to use ES+Kibana etc. but found the very puzzling situation that for this CRAB Task [1]
I can not find in ES the jobs which completed at T2_TR_METU.
An example of such job (which completed successfully at that site a few hours ago) is e.g. [3]
So if the job ran, I am sure HTCondor knows about it, why it is not shown ?
Is me not looking in the right way, or something is wrong in the reporting ?

By the way way those jobs are in ES when running (although with incomplete
information, like missing CRAB_Id i.e. their ID inside the crab task), but somehow not as Completed [4]

[1]
Here are pointers in new and old dashboard.

https://monit-grafana.cern.ch/d/NvcuKTSiz/condor-jobs-test?orgId=6&var-task=181203_151212:areinsvo_crab_SingleMuon_Run2017F-31Mar2018-v1&var-user=areinsvo
http://dashb-cms-job.cern.ch/dashboard/templates/task-analysis/#user=areinsvo&refresh=0&table=Mains&p=1&records=25&activemenu=2&pattern=181203_151212%3Aareinsvo_crab_SingleMuon_Run2017F-31Mar2018-v1&task=&from=&till=&timerange=lastWeek

[3]
https://cmsweb.cern.ch/scheddmon/0122/cms1354/181203_151212:areinsvo_crab_SingleMuon_Run2017F-31Mar2018-v1/job_out.30.0.txt

[4]
https://monit-kibana.cern.ch/kibana/app/kibana#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-24h,mode:quick,to:now))&_a=(columns:!(data.RequestCpus,data.Site,data.MachineAttrCpus0,data.Status,data.CRAB_Id),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'monit_prod_condor_raw_metric_v002-*',key:data.Type,negate:!f,type:phrase,value:analysis),query:(match:(data.Type:(query:analysis,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!t,index:'monit_prod_condor_raw_metric_v002-*',key:data.RequestCpus,negate:!f,type:phrase,value:'4'),query:(match:(data.RequestCpus:(query:4,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!t,index:'monit_prod_condor_raw_metric_v002-*',key:data.Status,negate:!f,type:phrase,value:Completed),query:(match:(data.Status:(query:Completed,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!t,index:'monit_prod_condor_raw_metric_v002-*',key:data.JobStatus,negate:!f,type:phrase,value:'4'),query:(match:(data.JobStatus:(query:4,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'monit_prod_condor_raw_metric_v002-*',key:data.Site,negate:!f,type:phrase,value:T2_TR_METU),query:(match:(data.Site:(query:T2_TR_METU,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'monit_prod_condor_raw_metric_v002-*',key:data.CRAB_Workflow,negate:!f,type:phrase,value:'181203_151212:areinsvo_crab_SingleMuon_Run2017F-31Mar2018-v1'),query:(match:(data.CRAB_Workflow:(query:'181203_151212:areinsvo_crab_SingleMuon_Run2017F-31Mar2018-v1',type:phrase))))),index:'monit_prod_condor_raw_metric_v002-*',interval:auto,query:(match_all:()),sort:!(data.MachineAttrCpus0,desc))

**Comment by belforte** [comment]
It is certainly an odd situation, some jobs in the task are reported, others are not, but somehow the problem should be at the HTC/MONIT boundary.
Do we have records of what we report ?

**Comment by stiegerb** [comment]
Hi Stefano,
I can find the completed document for your example job on es-cms: https://es-cms.cern.ch/kibana/goto/010bc6db398e1ae313cde573d02fdfa8
But, as you write, on monit-kibana there are only the intermitted documents for when the job was idle and running.

Since both es-cms and monit are fed from the same source with the same documents now, we can exclude a problem on our side. I suspect this is related to the issue with missing documents I reported, which is caused by the type mappings on monit-kibana, see [here](https://cern.service-now.com/service-portal/view-incident.do?n=INC1835331).

I will follow up with the monit team there. For your usecase, I suggest using es-cms for now. Also note that these jobs should be included in the influxdb aggregations that go into the job monitoring dashboard.

Cheers,
Benjamin
