### ISSUE TITLE
Add joblog and postJobLog urls

### ISSUE THREAD

**Issue by cronosnull** [dmwm/cms-htcondor-es#90]
In order to avoid using javascript links to create the URLs, we'll send the URLs to ES. 
Also, in order to use the value directly, we'll add the committed wall clock in seconds (to use the Grafana's duration formats).

**Comment by belforte** [comment]
constructing the URL here is a step forward from doing it in Javascript, but the best thing would be to do al lthe work on CRAB side. Re-formatting in here must be kept to minimun.

**Comment by cronosnull** [comment]
Already in CRAB now.
