### ISSUE TITLE
Add CRAB_Retry and QDate for Idle and running tasks

### ISSUE THREAD

**Issue by cronosnull** [dmwm/cms-htcondor-es#95]
In the new ES schema, the retry number is part of the ID of the document, it is needed to avoid duplicates. 

The QDate can be useful for the user in the tasks list for the running and pending tasks to order (and, when grafana enables us to do so, filter) the jobs.

**Comment by stiegerb** [comment]
Isn't the GlobalJobId enough to avoid duplicates, no matter the schema?

For the QDate, just go ahead and open a PR and I'll merge it right away.

**Comment by cronosnull** [comment]
Yes, the GlobalJobId works, I'll propose to use it as id in the new index (currently it is not there) instead of the current 3 fields concatenation. Can we add the CRAB_Retry anyway? the old dashboards show that number also for running tasks. 

Do you know why it is not used as Id in the condor_raw_metrics index? It seems a timestamp is added, causing the duplicates. Are we using this index for historical information? -If this is the same id used on influxdb, then makes sense-. 

I'm testing the change and will make the push later today.

**Comment by stiegerb** [comment]
Sure, we can add CRAB_Retry if it's interesting to look at.

We can't use GlobalJobId as the **document** id, since there are many documents for each job. So we concatenate it with the RecordTime to generate a unique id per document.
